In [30]:

%run "../SDFC/__TransitionsMCMC.py"


# Test Transitions Fuctions
## Fixed

In [28]:
x=np.array([0,0,0,0,0])
tran_scale_G=np.array([5])
transition_fixed(x,tran_scale_G)

array([ 2.46078548, -8.85498282,  8.24093496, -4.96826256,  9.14777471])

In [29]:
tran_scale_G=np.array([1,2,3,4,5])
transition_fixed(x,tran_scale_G)

array([ 0.66191076, -3.64913856, -1.40163995, -4.48988893,  1.53338193])

## MH Adaptative

In [32]:
draw=np.array([[0,0,0,0,0],[1,2,3,4,5],[5,4,3,2,1],[1,0,2,5,6],[5,5,4,7,0]])

i=1
transition_adaptative(x,i,draw,init=0.01,epsilon=0.01)

array([-0.14659388,  0.00419156,  0.10995274, -0.05018249, -0.16885075])

ModuleNotFoundError: No module named 'SDFC'

In [33]:
i=500
transition_adaptative(x,i,draw,init=0.01,epsilon=0.01)

array([-3.87780819, -2.58617866, -1.23481487, -0.72438406,  1.88378573])

In [34]:
i=1000
transition_adaptative(x,i,draw,init=0.01,epsilon=0.01)

array([-0.54440903,  0.6208113 , -1.08478282, -2.9266366 , -4.76093433])

In [ ]:
## MH-WG Adaptative

## Testing on full algorithm
Only with GEV
### MH

In [4]:
import SDFC as sd

In [5]:
import numpy as np
import scipy.stats as sc

In [6]:


n_samples=1000
n_mcmc_drawn=1000
prior_law=sc.multivariate_normal( mean = [0,0,0] , cov = np.identity(3)*(1) , allow_singular = True )

In [7]:


kwargs = { "n_samples" : n_samples ,
"name"    : "GEV" ,
"sd_law"  : sd.GEV() ,
"params"  : ["loc","scale","shape"] ,
"shape_p" : False}



In [8]:
#Ok run. Fixed, one scale
kwargs["transition_type"]="Fixed"
kwargs["fixed_cov"]=np.array([0.5])
ns_law=sd.GEV()
Yo     = np.random.normal( loc = [1] , scale = [2] , size = 150 )
ns_law._method="bayesian"
ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
ns_law.loc

fit0


/home/barbauxo/Documents/05_Autres Activités/2023_11_Transfert_Code_Yoann/SDFC-python/SDFC/__AbstractLaw.py:315: RuntimeWarning: invalid value encountered in scalar subtract
  p_accept = np.exp( p_next - p_current )


array([0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480241,
       0.17480241, 0.17480241, 0.17480241, 0.17480241, 0.17480

In [9]:
#Ok run. Fixed, dif scale
kwargs["transition_type"]="Fixed"
kwargs["fixed_cov"]=np.array([0.5,0.1,0.2])
ns_law=sd.GEV()
Yo     = np.random.normal( loc = [1] , scale = [2] , size = 150 )
ns_law._method="bayesian"
ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
ns_law.loc

fit0


array([0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070708,
       0.18070708, 0.18070708, 0.18070708, 0.18070708, 0.18070

In [10]:
#Ok run. adaptative
kwargs["transition_type"]="Adapt"

ns_law=sd.GEV()
Yo     = np.random.normal( loc = [1] , scale = [2] , size = 150 )
ns_law._method="bayesian"
ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
ns_law.loc

fit0
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt

/home/barbauxo/Documents/05_Autres Activités/2023_11_Transfert_Code_Yoann/SDFC-python/SDFC/__AbstractLaw.py:315: RuntimeWarning: overflow encountered in exp
  p_accept = np.exp( p_next - p_current )


Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adapt
Adap

array([0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721765,
       0.09721765, 0.09721765, 0.09721765, 0.09721765, 0.09721

# Test MH-WG

In [1]:
import SDFC as sd
import numpy as np
import scipy.stats as sc

In [2]:
n_samples=1000
n_mcmc_drawn=1000
prior_law=sc.multivariate_normal( mean = [0,0,0] , cov = np.identity(3)*(1) , allow_singular = True )
kwargs = { "n_samples" : n_samples ,
"name"    : "GEV" ,
"sd_law"  : sd.GEV() ,
"params"  : ["loc","scale","shape"] ,
"shape_p" : False}

In [3]:
#Ok run. Fixed, all scales 
kwargs["transition_type"]="Fixed"
kwargs["fixed_cov"]=np.array([0.5,0.2,0.3])
ns_law=sd.GEV()
Yo     = np.random.normal( loc = [1] , scale = [2] , size = 150 )
ns_law._method="bayesian-experimental"
ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
ns_law.loc

fit
[0.5 0.2 0.3]
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.

/home/barbauxo/Documents/05_Autres Activités/2023_11_Transfert_Code_Yoann/SDFC-python/SDFC/__AbstractLaw.py:488: RuntimeWarning: invalid value encountered in scalar subtract
  p_accept = np.exp( p_next - p_current )


0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3
0.5
0.2
0.3


array([-0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00249667,
       -0.00249667, -0.00249667, -0.00249667, -0.00249667, -0.00

In [11]:
#Ok run. adaptative
kwargs["transition_type"]="Adapt"

ns_law=sd.GEV()
Yo     = np.random.normal( loc = [1] , scale = [2] , size = 150 )
ns_law._method="bayesian-experimental"
ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
ns_law.loc

fit
Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/barbauxo/miniconda3/envs/TestSDFC/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_51584/2970197091.py", line 7, in <module>
    ns_law.fit( Yo , n_mcmc_drawn =  n_mcmc_drawn , prior=prior_law , **kwargs )
  File "/home/barbauxo/Documents/05_Autres Activités/2023_11_Transfert_Code_Yoann/SDFC-python/SDFC/__AbstractLaw.py", line 361, in fit
    self._fit_Bayesian_MHWG(**kwargs)
  File "/home/barbauxo/Documents/05_Autres Activités/2023_11_Transfert_Code_Yoann/SDFC-python/SDFC/__AbstractLaw.py", line 475, in _fit_Bayesian_MHWG
UnboundLocalError: cannot access local variable 'tran_scale_G' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/barbauxo/miniconda3/envs/TestSDFC/lib/python3.12/site-packages/IPython/core/interacti